name: ğŸ““ New charts
description: Submit a proposal for new charts
title: '[Playbook]: '
labels: ['playbook']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: country
    attributes:
      label: Country
      description: What country charts are you requesting?
      placeholder: India (IN)
    validations:
      required: true
  - type: input
    id: eaip
    attributes:
      label: eAIP
      description: Country eAIP website
      placeholder: https://...
    validations:
      required: true
  - type: input
    id: steps
    attributes:
      label: Steps to add a new playbook
      value: https://github.com/drph4nt0m/avbot-charts/wiki/Playbooks
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "ğŸ‘€ Have you spent some time to check if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues for a similar bug?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "ğŸ¢ Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/drph4nt0m/avbot-charts/blob/HEAD/CODE_OF_CONDUCT.md)"
          required: true
